name: CMake Build and Test

on:
  push:
  workflow_dispatch:

jobs:
  build-linux:
    name: Build on Linux with GCC
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.21.1'

      - name: Install dependencies
        run: |
          sudo apt-get install -y build-essential libsdl2-dev libfreetype-dev

      - name: Configure and Build
        run: |
          mkdir build
          cd build
          cmake ..
          make fontconv

  build-platformio:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example: [examples/arduino/helloworld-stm32-st7789/, examples/gammacalibration-stm32-st7789, helloworld-stm32-st7789]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO examples
        run: pio ci --board=bluepill_f103c8 --lib=src
        env:
          PLATFORMIO_CI_SRC: ${{ matrix.example }}
