name: CMake Build and Test

on:
  push:
  workflow_dispatch:

jobs:
  build-linux:
    name: Build on Linux with GCC
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.21.1'

      - name: Install dependencies
        run: |
          sudo apt-get install -y build-essential libsdl2-dev libfreetype-dev

      - name: Configure and Build
        run: |
          mkdir build
          cd build
          cmake ..
          make fontconv
          make
